import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { PlanProvider } from "@/context/PlanContext";
import { AttemptedQuestionProvider } from "@/context/AttemptedQuestionContext";
import { SelectedTopicsProvider } from "@/context/SelectedTopicsContext";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <PlanProvider>
        <AttemptedQuestionProvider>
          <SelectedTopicsProvider>
            <html lang="en">
              <body className={`${inter.className} antialiased`}>
                {children}
              </body>
            </html>
          </SelectedTopicsProvider>
        </AttemptedQuestionProvider>
      </PlanProvider>
    </ClerkProvider>
  );
}
