import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {PlanProvider} from "@/context/PlanContext";
import { AttemptedQuestionProvider } from "@/context/AttemptedQuestionContext";
import { SelectedTopicsProvider } from "@/context/SelectedTopicsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({  
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <PlanProvider>
        <AttemptedQuestionProvider>
          <SelectedTopicsProvider>
            <html lang="en">
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                {children}
              </body>
            </html>
          </SelectedTopicsProvider>
        </AttemptedQuestionProvider>
      </PlanProvider>
    </ClerkProvider>
  );
}
